# Generated by Django 4.1.7 on 2023-02-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image", models.ImageField(upload_to="products/")),
                ("available_colors", models.CharField(max_length=255)),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="product_videos/"
                    ),
                ),
                ("sizes", models.CharField(max_length=255)),
                ("rating", models.IntegerField()),
                ("categories", models.ManyToManyField(to="myapp.category")),
            ],
        ),
    ]
